FROM centos/php-56-centos7:latest
ARG WORDPRESS_VERSION
ARG WORDPRESS_SHA1
ENV WORDPRESS_VERSION=${WORDPRESS_VERSION:-4.5} \
    WORDPRESS_SHA1=${WORDPRESS_SHA1:-439f09e7a948f02f00e952211a22b8bb0502e2e2} \
    NODEJS_VERSION=8 \
    NPM_RUN=start \
    NPM_CONFIG_PREFIX=$HOME/.npm-global \
    PATH=$HOME/node_modules/.bin/:$HOME/.npm-global/bin/:$PATH

VOLUME /opt/app-root/wp-content

# Add nodejs 8 and php apcu cache
USER root
RUN yum install -y centos-release-scl-rh && \
    yum remove -y rh-nodejs6\* && \
    yum-config-manager --enable centos-sclo-rh-testing && \
    INSTALL_PKGS="rh-nodejs8 rh-nodejs8-npm rh-nodejs8-nodejs-nodemon nss_wrapper sclo-php56-php-pecl-apcu" && \
    ln -s /usr/lib/node_modules/nodemon/bin/nodemon.js /usr/bin/nodemon && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y
# Install wordpress and backup the base image S2I scripts
RUN env && cd /tmp && curl -o wordpress.tar.gz -SL https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz \
    && mkdir -p /opt/app-root/wordpress \
    && echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c - \
    && tar -xzf wordpress.tar.gz --strip-components=1 -C /opt/app-root/wordpress \
    && rm wordpress.tar.gz \
    && mv /opt/app-root/wordpress/wp-content /opt/app-root/wordpress/wp-content-install \
    && mv $STI_SCRIPTS_PATH/run $STI_SCRIPTS_PATH/run-base \
    && mv $STI_SCRIPTS_PATH/assemble $STI_SCRIPTS_PATH/assemble-base \
    && fix-permissions /opt/app-root/wordpress \
    && fix-permissions /opt/app-root/wp-content && chmod -R 0777 /opt/app-root/wp-content


# Copied from the official Wordpress Docker image
RUN { \
      echo 'opcache.memory_consumption=128'; \
      echo 'opcache.interned_strings_buffer=8'; \
      echo 'opcache.max_accelerated_files=4000'; \
      echo 'opcache.revalidate_freq=60'; \
      echo 'opcache.fast_shutdown=1'; \
      echo 'opcache.enable_cli=1'; \
      } > /etc/opt/rh/rh-php56/php.d/11-opcache-wordpress.ini

# Add root
COPY ./root/ /

# Install config templates
COPY contrib/* /opt/app-root/wordpress/

# Add certs
RUN mv -f /opt/app-root/wordpress/*.crt /etc/pki/ca-trust/source/anchors/ \
  && update-ca-trust

# Install wordpress S2I scripts
COPY s2i/bin/* $STI_SCRIPTS_PATH/
USER 1001
