[[s2i-wordpress-image]]
= Go Docker images

This repository contains the source for creating a
https://github.com/openshift/source-to-image[source-to-image] builder image,
which can be used to create reproducible Docker images with Wordpress[https://wordpress.org].

For more information about using these images with OpenShift, please see
the official
https://docs.openshift.org/latest/using_images/s2i_images/php.html[OpenShift
Documentation].

[[versions]]
== Versions

Wordpress versions currently supported are:

* Wordpress 4.5


[[copyright-license]]
Copyright and License
~~~~~~~~~~~~~~~~~~~~~

Copyright 2016 by Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this package except in compliance with the License (see the `LICENSE` file
included in this distribution). You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
